update workflow

diff --git a/.github/workflows/postman.yaml b/.github/workflows/postman.yaml
--- a/.github/workflows/postman.yaml
+++ b/.github/workflows/postman.yaml
@@ -29,7 +29,7 @@ jobs:
           if: success() || failure()
           run: |
             newman run  https://api.getpostman.com/collections/19980843-e1ea76f0-dc90-4e50-9992-f68ac667e706?apikey=${{ secrets.postmanApiKey }} \
-            -r allure --reporter-allure-export allure-results 
+            -r slackreporter,allure --reporter-allure-export allure-results --reporter-slackreporter-webhookurl ${{ secrets.SLACK_WEBHOOK_URL }}  
             wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure_2.18.1-1_all.deb
             sudo dpkg -i allure_2.18.1-1_all.deb
             allure generate --clean
@@ -40,15 +40,15 @@ jobs:
             name: Allure-Reports
             path: allure-report
 
-        - name: Generate html report
-          if: success() || failure()
-          run: |
-            newman run  https://api.getpostman.com/collections/19980843-e1ea76f0-dc90-4e50-9992-f68ac667e706?apikey=${{ secrets.postmanApiKey }} \
-             -r slackreporter,htmlextra --reporter-htmlextra-export testArtifactsHTML/htmlreport.html --reporter-slackreporter-webhookurl ${{ secrets.SLACK_WEBHOOK_URL }}  
-        # Upload the reports to TestArtifacts directory
-        - name: Output the results
-          if: always()
-          uses: actions/upload-artifact@v2
-          with:
-            name: Reports
-            path: testArtifactsHTML
+        # - name: Generate html report
+        #   if: success() || failure()
+        #   run: |
+        #     newman run  https://api.getpostman.com/collections/19980843-e1ea76f0-dc90-4e50-9992-f68ac667e706?apikey=${{ secrets.postmanApiKey }} \
+        #      -r slackreporter,htmlextra --reporter-htmlextra-export testArtifactsHTML/htmlreport.html 
+        # # Upload the reports to TestArtifacts directory
+        # - name: Output the results
+        #   if: always()
+        #   uses: actions/upload-artifact@v2
+        #   with:
+        #     name: Reports
+        #     path: testArtifactsHTML
